# Generated by Django 3.2.8 on 2021-12-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='position',
            field=models.IntegerField(blank=True, null=True, verbose_name='Position'),
        ),
    ]
