# Generated by Django 3.2.8 on 2021-12-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transactions_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
    ]
