# Generated by Django 3.2.8 on 2021-12-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Fullname')),
                ('address', models.CharField(max_length=256, verbose_name='Fullname')),
                ('checked', models.BooleanField(blank=True, null=True)),
                ('description', models.CharField(max_length=256, verbose_name='Fullname')),
                ('interest', models.CharField(max_length=256, verbose_name='Interest')),
                ('date_of_birth', models.DateTimeField(verbose_name='Date of Birth')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email address.')),
                ('account', models.IntegerField(blank=True, null=True, verbose_name='Account No')),
                ('credit_card', models.JSONField()),
            ],
        ),
    ]
