# Generated by Django 3.2.8 on 2021-12-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customers_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
