# Generated by Django 3.2.8 on 2021-12-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customers_created_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='interest',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Interest'),
        ),
    ]
